### ISSUE TITLE
TypeError when creating a cluster with a string optional component in version 2.0.0

### ISSUE THREAD

**Issue by TusharK54** [googleapis/python-dataproc#80]
#### Environment details

  - OS type and version: Debian GNU/Linux 10 (buster) on Chrome OS x86_64 (version 84.0.4147.110)
  - Python version: 3.7.3
  - pip version: 18.1
  - `google-cloud-dataproc` version: 2.0.0
    - This issue does not occur in versions 0.8.0 and 1.1.1.

#### Steps to reproduce

1. Create a Dataproc cluster configuration with `optional_components` set to `["ANACONDA"]`.
    - Note that there is no error if we create a cluster configuration with `optional_components` set to `[5]`, which is the value of the `Component.ANACONDA` enum according to [this](https://github.com/googleapis/python-dataproc/blob/master/google/cloud/dataproc_v1/proto/shared.proto).
2. Use the cluster configuration to create a cluster with the `create_cluster` method of a `google.cloud.dataproc_v1.services.cluster_controller.ClusterControllerClient` object.

#### Code example

```python
import os
import uuid
from google.cloud import dataproc_v1 as dataproc

PROJECT_ID = os.environ["GOOGLE_CLOUD_PROJECT"]
TEST_ID = uuid.uuid4()
DATAPROC_CLUSTER = f"clean-test-{TEST_ID}"
CLUSTER_REGION = "us-central1"
CLUSTER_IMAGE = "1.5.4-debian10"
CLUSTER_CONFIG = {
    "project_id": PROJECT_ID,
    "cluster_name": DATAPROC_CLUSTER,
    "config": {
        "gce_cluster_config": {
            "zone_uri": "",
            "metadata": {"PIP_PACKAGES": "google-cloud-storage"},
        },
        "master_config": {"num_instances": 1, "machine_type_uri": "n1-standard-8"},
        "worker_config": {"num_instances": 6, "machine_type_uri": "n1-standard-8"},
        "software_config": {
            "image_version": CLUSTER_IMAGE,
            "optional_components": ["ANACONDA"], # No error when "ANACONDA" is changed to 5
        },
    },
}

cluster_client = dataproc.ClusterControllerClient(
    client_options={"api_endpoint": f"{CLUSTER_REGION}-dataproc.googleapis.com:443"}
)
operation = cluster_client.create_cluster(
    project_id=PROJECT_ID, region=CLUSTER_REGION, cluster=CLUSTER_CONFIG
)
```

#### Stack trace
```
Traceback (most recent call last):
  File "issue.py", line 31, in <module>
    project_id=PROJECT_ID, region=CLUSTER_REGION, cluster=CLUSTER_CONFIG
  File "/home/tusharkhan/.local/lib/python3.7/site-packages/google/cloud/dataproc_v1/services/cluster_controller/client.py", line 309, in create_cluster
    request.cluster = cluster
  File "/home/tusharkhan/.local/lib/python3.7/site-packages/proto/message.py", line 534, in __setattr__
    pb_value = marshal.to_proto(pb_type, value)
  File "/home/tusharkhan/.local/lib/python3.7/site-packages/proto/marshal/marshal.py", line 205, in to_proto
    pb_value = rule.to_proto(value)
  File "/home/tusharkhan/.local/lib/python3.7/site-packages/proto/marshal/rules/message.py", line 32, in to_proto
    return self._descriptor(**value)
TypeError: 'ANACONDA' has type str, but expected one of: int, long
```

**Comment by bradmiro** [comment]
Was able to reproduce this. @busunkim96 any ideas?

**Comment by busunkim96** [comment]
@bradmiro I think this might be related to https://github.com/googleapis/proto-plus-python/issues/52.  @software-dov could you take a look? 

A more readable work around is to use the `Component` type.  It doesn't seem to show up in the generated documentation but the file is [here](https://github.com/googleapis/python-dataproc/blob/108d6ff91c6442e743cdf449790f981709305a09/google/cloud/dataproc_v1/types/shared.py). 
```py
from google.cloud import dataproc_v1 as dataproc

component = dataproc.Component.ANACONDA
``` 


```py
import os
import uuid
from google.cloud import dataproc_v1 as dataproc

PROJECT_ID = os.environ["GOOGLE_CLOUD_PROJECT"]
TEST_ID = uuid.uuid4()
DATAPROC_CLUSTER = f"clean-test-{TEST_ID}"
CLUSTER_REGION = "us-central1"
CLUSTER_IMAGE = "1.5.4-debian10"
CLUSTER_CONFIG = {
    "project_id": PROJECT_ID,
    "cluster_name": DATAPROC_CLUSTER,
    "config": {
        "gce_cluster_config": {
            "zone_uri": "",
            "metadata": {"PIP_PACKAGES": "google-cloud-storage"},
        },
        "master_config": {"num_instances": 1, "machine_type_uri": "n1-standard-8"},
        "worker_config": {"num_instances": 6, "machine_type_uri": "n1-standard-8"},
        "software_config": {
            "image_version": CLUSTER_IMAGE,
            "optional_components": [dataproc.Component.ANACONDA],
        },
    },
}

cluster_client = dataproc.ClusterControllerClient(
    client_options={"api_endpoint": f"{CLUSTER_REGION}-dataproc.googleapis.com:443"}
)
operation = cluster_client.create_cluster(
    project_id=PROJECT_ID, region=CLUSTER_REGION, cluster=CLUSTER_CONFIG
)
```

**Comment by software-dov** [comment]
This is similar to but technically distinct from https://github.com/googleapis/proto-plus-python/issues/52; it is a problem with marshaling stringy enums from Python, not from JSON.
I'm fairly certain that most of the work for fixing stringy JSON enums will apply to this. I'll close this and open a new issue on proto-plus.

**Comment by software-dov** [comment]
Tracked by https://github.com/googleapis/proto-plus-python/issues/103
